# Claude Code Hooks Configuration
# This file centralizes all hook configurations
# Update these settings to customize hook behavior

# Stop Hook - Runs when Claude Code finishes responding
stop:

# Notification Hook - Runs when Claude sends notifications
notification:

# SubagentStop Hook - Runs when subagent tasks complete
subagent_stop:

# UserPromptSubmit Hook - Runs when user submits a prompt
user_prompt_submit:

# PreToolUse Hook - Runs before tool calls
pre_tool_use:

# PostToolUse Hook - Runs after tool calls complete  
post_tool_use:

# PreCompact Hook - Runs before context compaction
pre_compact:

# SessionStart Hook - Runs when session starts/resumes
session_start:
  # Conversation capture configuration
  conversation_capture:
    enabled: true # Enable conversation capture
    module: "conversation_capture.main" # Module to use for conversation capture
    function: "start_conversation_capture" # Function to use for conversation capture
    config:
      pid_file_name: "conversation_watchdog.pid" # Name of PID file for conversation watchdog
      episodic_path: ".claude/agents/memory/episodic" # Directory for episodic memory files
      human_name: "Saito" # Human name for conversation
      agent_name: "The Architect" # Primary agent for conversation

# SessionEnd Hook - Runs when session ends
session_end:
  # Cleanup subprocesses configuration
  cleanup_subprocesses:
    enabled: true # Enable cleanup subprocesses
    module: "cleanup_subprocesses.main" # Module to use for cleanup subprocesses
    function: "cleanup_subprocesses" # Function to use for cleanup subprocesses
    config:

# Global Settings - Apply to all hooks
# API Keys and URLs are loaded from .env file
global:
  # Logging
  log_directory: "logs" # Directory for all log files
  # Performance
  subprocess_timeout: 10 # Timeout for subprocess calls (seconds)
  # Debug
  verbose_errors: false # Show detailed error messages
